<?php
/** Executable M5 provision/status contract harness. */
define( 'ABSPATH', __DIR__ ); define( 'DAY_IN_SECONDS', 86400 ); define( 'ARRAY_A', 'ARRAY_A' );
define( 'AUTH_KEY', 'm5-auth-key' ); define( 'SECURE_AUTH_KEY', 'm5-secure-key' ); define( 'LOGGED_IN_KEY', 'm5-login-key' ); define( 'NONCE_KEY', 'm5-nonce-key' );
function m5_assert( $condition, $message ) { if ( ! $condition ) { fwrite( STDERR, "FAIL: {$message}\n" ); exit( 1 ); } }
function wp_json_encode( $value ) { return json_encode( $value ); } function absint( $value ) { return abs( (int) $value ); }
function sanitize_text_field( $value ) { return trim( strip_tags( (string) $value ) ); } function wp_strip_all_tags( $value ) { return strip_tags( (string) $value ); }
function sanitize_user( $value ) { return preg_replace( '/[^A-Za-z0-9._-]/', '', (string) $value ); } function is_email( $value ) { return false !== filter_var( $value, FILTER_VALIDATE_EMAIL ); } function sanitize_email( $value ) { return trim( (string) $value ); }
function wp_generate_password( $length = 12 ) { return str_repeat( 'x', $length ); }
if ( ! defined( 'OPENSSL_RAW_DATA' ) ) { define( 'OPENSSL_RAW_DATA', 1 ); } if ( ! function_exists( 'openssl_encrypt' ) ) { function openssl_encrypt( $data ) { return $data; } function openssl_decrypt( $data ) { return $data; } }
class WP_Error { public $code; public $message; public $data; public function __construct( $code, $message = '', $data = array() ) { $this->code = $code; $this->message = $message; $this->data = $data; } public function get_error_code() { return $this->code; } public function get_error_message() { return $this->message; } public function get_error_data() { return $this->data; } }
function is_wp_error( $value ) { return $value instanceof WP_Error; }
class WP_REST_Response { public $data; public $status; public function __construct( $data, $status = 200 ) { $this->data = $data; $this->status = $status; } public function get_data() { return $this->data; } public function get_status() { return $this->status; } }
class M5_Request { private $headers; private $body; private $params; private $route; public function __construct( $headers, $body, $route, $params = array() ) { $this->headers = $headers; $this->body = $body; $this->route = $route; $this->params = $params; } public function get_header( $name ) { return $this->headers[ strtolower( $name ) ] ?? ''; } public function get_body() { return $this->body; } public function get_json_params() { return json_decode( $this->body, true ); } public function get_param( $name ) { return $this->params[ $name ] ?? null; } public function get_route() { return $this->route; } public function get_method() { return 'POST'; } }
class M5_User { public $ID; public $user_email; public function __construct( $id, $email ) { $this->ID = $id; $this->user_email = $email; } }
class M5_WPDB {
 public $prefix = 'wp_'; public $insert_id = 0; public $rows = array(); public $audit = array(); public $bindings = array();
 public $tables = array( 'wp_yby_connector_idempotency', 'wp_yby_connector_audit', 'wp_yby_connector_affiliate_bindings' );
 public $indexes = array( 'wp_yby_connector_idempotency' => array( array( 'Key_name'=>'mutation_identity','Non_unique'=>0 ) ), 'wp_yby_connector_affiliate_bindings' => array( array( 'Key_name'=>'connection_kol','Non_unique'=>0 ), array( 'Key_name'=>'connection_affiliate','Non_unique'=>0 ) ) ); public $renew_noop = false;
 public function get_charset_collate() { return ''; }
 public function prepare( $query, ...$args ) { foreach ( $args as $arg ) { $query = preg_replace( '/%[sd]/', is_string( $arg ) ? "'" . $arg . "'" : (string) $arg, $query, 1 ); } return $query; }
 private function duplicate_binding( $data, $ignore_id = null ) { foreach ( $this->bindings as $row ) { if ( null !== $ignore_id && (int) ( $row['id'] ?? 0 ) === (int) $ignore_id ) continue; if ( $row['connection_key'] === $data['connection_key'] && (int) $row['erp_kol_id'] === (int) $data['erp_kol_id'] && null === ( $data['affiliate_id'] ?? null ) ) return true; if ( $row['connection_key'] === $data['connection_key'] && null !== $data['affiliate_id'] && null !== ( $row['affiliate_id'] ?? null ) && (int) $row['affiliate_id'] === (int) $data['affiliate_id'] && (int) $row['erp_kol_id'] !== (int) $data['erp_kol_id'] ) return true; } return false; }
 public function insert( $table, $data ) { if ( false !== strpos( $table, 'idempotency' ) ) { foreach ( $this->rows as $row ) if ( $row['mutation_identity_hash'] === $data['mutation_identity_hash'] ) return false; $data['id'] = ++$this->insert_id; $this->rows[] = $data; return 1; } if ( false !== strpos( $table, 'bindings' ) ) { if ( $this->duplicate_binding( $data ) ) return false; $data['id'] = ++$this->insert_id; $this->bindings[] = $data; return 1; } $data['id'] = ++$this->insert_id; $this->audit[] = $data; return 1; }
 public function get_row( $query ) { if ( false !== strpos( $query, 'mutation_identity_hash' ) ) { preg_match( "/mutation_identity_hash = '([^']+)'/", $query, $m ); foreach ( $this->rows as $row ) if ( ( $m[1] ?? '' ) === $row['mutation_identity_hash'] ) return $row; } elseif ( false !== strpos( $query, 'FROM wp_yby_connector_affiliate_bindings' ) ) { preg_match( "/connection_key = '([^']+)' AND (erp_kol_id|affiliate_id) = (\d+)/", $query, $m ); foreach ( $this->bindings as $row ) if ( ( $m[1] ?? '' ) === $row['connection_key'] && null !== ( $row[ $m[2] ?? 'erp_kol_id' ] ?? null ) && (int) $row[ $m[2] ?? 'erp_kol_id' ] === (int) $m[3] ) return $row; } elseif ( preg_match( '/WHERE id = (\d+)/', $query, $m ) ) { foreach ( $this->rows as $row ) if ( (int) $row['id'] === (int) $m[1] ) return $row; } return null; }
 public function query( $query ) { if ( preg_match( "/WHERE id = (\d+).*state = 'failed'/", $query, $m ) ) { foreach ( $this->rows as &$row ) if ( (int) $row['id'] === (int) $m[1] && 'failed' === $row['state'] && ! empty( $row['retryable'] ) ) { $row['state'] = 'processing'; return 1; } } if ( ! preg_match( "/UPDATE .*bindings SET (.*) WHERE connection_key = '([^']+)' AND erp_kol_id = (\d+)/", $query, $m ) ) return 0; foreach ( $this->bindings as &$row ) { if ( $row['connection_key'] !== $m[2] || (int) $row['erp_kol_id'] !== (int) $m[3] ) continue; $owner = array(); preg_match( "/lease_owner_hash = '([^']+)'/", $query, $owner ); $owner = $owner[1] ?? null; $takeover = false !== strpos( $query, 'lease_expires_at < UTC_TIMESTAMP()' ); if ( $takeover && ( 'processing' !== (string) $row['state'] || empty( $row['lease_expires_at'] ) || strtotime( $row['lease_expires_at'] ) >= time() ) ) return 0; if ( false !== strpos( $m[1], 'lease_owner_hash = NULL' ) ) { if ( null === $owner || (string) $row['lease_owner_hash'] !== (string) $owner ) return 0; preg_match( '/wp_user_id = (\d+)/', $m[1], $user ); preg_match( '/affiliate_id = (\d+)/', $m[1], $affiliate ); $candidate = array( 'connection_key'=>$row['connection_key'], 'erp_kol_id'=>$row['erp_kol_id'], 'affiliate_id'=>(int) ( $affiliate[1] ?? 0 ) ); if ( $this->duplicate_binding( $candidate ) ) return 0; $row['wp_user_id'] = (int) ( $user[1] ?? 0 ); $row['affiliate_id'] = $candidate['affiliate_id']; $row['state'] = 'ready'; $row['lease_owner_hash'] = null; $row['lease_expires_at'] = null; return 1; } if ( ! $takeover && null !== $owner && (string) $row['lease_owner_hash'] !== (string) $owner ) return 0; if ( false !== strpos( $m[1], 'lease_owner_hash =' ) ) { $row['lease_owner_hash'] = $owner; $row['lease_expires_at'] = gmdate( 'Y-m-d H:i:s', time() + 300 ); $row['state'] = 'processing'; return 1; } if ( false !== strpos( $m[1], 'lease_expires_at = UTC_TIMESTAMP()' ) ) { $row['lease_expires_at'] = gmdate( 'Y-m-d H:i:s' ); return 1; } if ( false !== strpos( $m[1], 'lease_expires_at =' ) ) { if ( $this->renew_noop ) return 0; if ( false !== strpos( $query, 'lease_expires_at >= UTC_TIMESTAMP()' ) && ( empty( $row['lease_expires_at'] ) || strtotime( $row['lease_expires_at'] ) < time() ) ) return 0; $row['lease_expires_at'] = gmdate( 'Y-m-d H:i:s', time() + 300 ); return 1; } } return 0; }
 public function update( $table, $data, $where ) { foreach ( $this->rows as &$row ) if ( (int) $row['id'] === (int) $where['id'] && $row['state'] === $where['state'] ) { $row = array_merge( $row, $data ); return 1; } return 0; }
 public function get_results( $query, $format = null ) { return $this->audit; } public function get_var( $query ) { preg_match( "/SHOW TABLES LIKE '([^']+)'/", $query, $m ); return in_array( $m[1] ?? '', $this->tables, true ) ? ( $m[1] ?? '' ) : null; } public function get_col() { return array(); }
}
$wpdb = new M5_WPDB(); $m5_options = array(); $m5_transients = array(); $m5_users = array(); $m5_affiliates = array(); $m5_provider = true; $m5_mutations = 0; $m5_user_writes = 0;
function get_option( $key, $default = false ) { global $m5_options; return array_key_exists( $key, $m5_options ) ? $m5_options[ $key ] : $default; } function add_option( $key, $value ) { global $m5_options; if ( array_key_exists( $key, $m5_options ) ) return false; $m5_options[ $key ] = $value; return true; } function update_option( $key, $value ) { global $m5_options; $m5_options[ $key ] = $value; return true; }
function get_transient( $key ) { global $m5_transients; return $m5_transients[ $key ] ?? false; } function set_transient( $key, $value, $ttl ) { global $m5_transients; $m5_transients[ $key ] = $value; return true; } function is_ssl() { return true; } function get_bloginfo() { return '6.0'; } function register_rest_route() {}
function username_exists( $login ) { global $m5_users; foreach ( $m5_users as $user ) if ( $user['login'] === $login ) return $user['id']; return false; } function get_user_by( $field, $value ) { global $m5_users; foreach ( $m5_users as $user ) if ( ( 'email' === $field && strtolower( $user['email'] ) === strtolower( $value ) ) || ( 'id' === $field && (int) $user['id'] === (int) $value ) ) return new M5_User( $user['id'], $user['email'] ); return false; }
function wp_insert_user( $data ) { global $m5_users, $m5_user_writes; ++$m5_user_writes; if ( username_exists( $data['user_login'] ) ) return new WP_Error( 'existing_user' ); $id = count( $m5_users ) + 1; $m5_users[] = array( 'id'=>$id, 'login'=>$data['user_login'], 'email'=>$data['user_email'] ); return $id; }
function affiliate_wp() { global $m5_provider; return $m5_provider ? (object) array() : null; } function affwp_get_affiliate_statuses() { return array( 'active'=>'Active', 'inactive'=>'Inactive', 'pending'=>'Pending' ); } function affwp_get_affiliate( $id ) { global $m5_affiliates; return $m5_affiliates[ (int) $id ] ?? false; } function affwp_get_affiliate_by( $field, $value ) { global $m5_affiliates; foreach ( $m5_affiliates as $affiliate ) if ( (int) $affiliate->user_id === (int) $value ) return $affiliate; return false; } function affwp_add_affiliate( $data ) { global $m5_affiliates, $m5_mutations; ++$m5_mutations; $id = empty( $m5_affiliates ) ? 1 : max( array_keys( $m5_affiliates ) ) + 1; $m5_affiliates[ $id ] = (object) array( 'affiliate_id'=>$id, 'user_id'=>$data['user_id'], 'status'=>$data['status'] ); return $id; } function affwp_set_affiliate_status( $id, $status ) { global $m5_affiliates, $m5_mutations; ++$m5_mutations; if ( ! isset( $m5_affiliates[ $id ] ) ) return false; $m5_affiliates[ $id ]->status = $status; return true; }
require_once dirname( __DIR__ ) . '/inc/class-yby-database.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector-idempotency.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector-audit.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-subscriber-snapshot.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector-affiliate-bindings.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector.php';
update_option( YBY_Connector::OPTION, array( 'enabled'=>true, 'connection_key'=>'site-a', 'key_id'=>'erp-key' ) ); $secret = YBY_Connector::generate_secret();
function m5_request( $route, $body, $key, $params = array() ) { $raw = json_encode( $body ); $timestamp = (string) time(); $nonce = 'nonce-' . $key . '-' . mt_rand( 1000, 9999 ); $headers = array( 'x-yby-connection-key'=>'site-a', 'x-yby-key-id'=>'erp-key', 'x-yby-timestamp'=>$timestamp, 'x-yby-nonce'=>$nonce, 'x-yby-idempotency-key'=>$key, 'x-yby-signature-version'=>'v1' ); $headers['x-yby-signature'] = YBY_Connector::sign( 'POST', '/wp-json/andy-core/v1/erp' . $route, $timestamp, $nonce, 'site-a', $key, $raw, 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' ); return new M5_Request( $headers, $raw, '/wp-json/andy-core/v1/erp' . $route, $params ); }
function m5_dispatch( $request, $operation, $action, $endpoint ) { $method = new ReflectionMethod( 'YBY_Connector', 'dispatch_mutation' ); $method->setAccessible( true ); $result = $method->invoke( null, $request, $action, $endpoint, $operation ); return $result instanceof WP_REST_Response && $result->get_status() < 400 ? $result->get_data() : $result; }
$base = array( 'erp_kol_id'=>11, 'email'=>'  PERSON@Example.TEST ', 'display_name'=>'Person', 'preferred_username'=>'person', 'requested_affiliate_status'=>'active', 'payment_email'=>'PAY@Example.TEST' ); $renew_owner = hash( 'sha256', 'renew-owner' ); $renew_reservation = YBY_Connector_Affiliate_Bindings::reserve( 'site-a', 22, $renew_owner ); m5_assert( 'acquired' === $renew_reservation['status'], 'Renew behavior test must acquire its reservation.' ); $wpdb->renew_noop = true; m5_assert( true === YBY_Connector_Affiliate_Bindings::renew( 'site-a', 22, $renew_owner ), 'Same-second no-op renew must succeed after authoritative owner readback.' ); m5_assert( false === YBY_Connector_Affiliate_Bindings::renew( 'site-a', 22, hash( 'sha256', 'wrong-owner' ) ), 'Renew must fail when the lease owner does not match.' ); foreach ( $wpdb->bindings as &$renew_row ) if ( 22 === (int) $renew_row['erp_kol_id'] ) { $renew_row['lease_expires_at'] = gmdate( 'Y-m-d H:i:s', time() - 10 ); } m5_assert( false === YBY_Connector_Affiliate_Bindings::renew( 'site-a', 22, $renew_owner ), 'Renew must fail after the lease expires.' ); $wpdb->renew_noop = false;
$race_owner = hash( 'sha256', 'race-owner' ); $race = YBY_Connector_Affiliate_Bindings::reserve( 'site-a', 20, $race_owner ); m5_assert( 'acquired' === $race['status'], 'First same-KOL request must acquire durable reservation.' ); $race_writes = $m5_user_writes + $m5_mutations; $race_blocked = m5_dispatch( m5_request( '/affiliates/provision', array_merge( $base, array( 'erp_kol_id'=>20 ) ), 'race-2' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( 409 === $race_blocked->get_status() && 'PROVISION_IN_PROGRESS' === $race_blocked->get_data()['code'] && true === $race_blocked->get_data()['retryable'] && $race_writes === $m5_user_writes + $m5_mutations, 'Concurrent different-key request must stop before provider mutation.' ); $race_user = wp_insert_user( array( 'user_login'=>'race-20', 'user_pass'=>'x', 'user_email'=>'race@example.test' ) ); $race_affiliate = affwp_add_affiliate( array( 'user_id'=>$race_user, 'status'=>'active' ) ); $race_bound = YBY_Connector_Affiliate_Bindings::finalize( 'site-a', 20, $race_owner, $race_user, $race_affiliate ); m5_assert( $race_bound && 'ready' === $race_bound['state'], 'Reservation owner must finalize atomically.' ); $race_retry = m5_dispatch( m5_request( '/affiliates/provision', array_merge( $base, array( 'erp_kol_id'=>20, 'email'=>'race@example.test' ) ), 'race-3' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( $race_retry['data']['wp_user_id'] === $race_user && $race_retry['data']['affiliate_id'] === $race_affiliate && $race_writes + 2 === $m5_user_writes + $m5_mutations, 'Later retry must return established IDs without provider mutation.' ); YBY_Connector_Affiliate_Bindings::reserve( 'site-a', 21, hash( 'sha256', 'stale-owner' ) ); foreach ( $wpdb->bindings as &$stale_row ) if ( 21 === (int) $stale_row['erp_kol_id'] ) { $stale_row['lease_expires_at'] = gmdate( 'Y-m-d H:i:s', time() - 10 ); } $takeover = YBY_Connector_Affiliate_Bindings::reserve( 'site-a', 21, hash( 'sha256', 'new-owner' ) ); m5_assert( 'acquired' === $takeover['status'] && ! empty( $takeover['recovered'] ), 'Expired reservation must be safely recoverable.' );
$audit_before = count( $wpdb->audit ); $first = m5_dispatch( m5_request( '/affiliates/provision', $base, 'p1' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( true === $first['ok'] && array_keys( $first['data'] ) === array( 'wp_user_id','affiliate_id','affiliate_status','created_user','created_affiliate' ), 'First provision must return complete five-field data.' ); $mutations = $m5_mutations;
$retry = m5_dispatch( m5_request( '/affiliates/provision', $base, 'p1' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( $retry['data'] === $first['data'] && $m5_mutations === $mutations, 'Exact retry must replay identical data without provider mutation.' ); m5_assert( count( $wpdb->audit ) === $audit_before + 2, 'Success and replay must both be audited.' );
$changed = $base; $changed['display_name'] = 'Changed'; $conflict = m5_dispatch( m5_request( '/affiliates/provision', $changed, 'p1' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( 409 === $conflict->get_status() && 'IDEMPOTENCY_CONFLICT' === $conflict->get_data()['code'], 'Changed payload must conflict.' );
$extra = $base; $extra['unexpected'] = true; $invalid = m5_dispatch( m5_request( '/affiliates/provision', $extra, 'p-extra' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( 400 === $invalid->get_status(), 'Unknown provision keys must be rejected.' );
$m5_affiliates[1]->status = 'inactive'; $status = m5_dispatch( m5_request( '/affiliates/1/status', array( 'status'=>'inactive' ), 's1', array( 'affiliate_id'=>'1' ) ), 'status', 'affiliate.status', '/affiliates/{affiliate_id}/status' ); m5_assert( true === $status['ok'], 'Status no-op must succeed.' ); $status2 = m5_dispatch( m5_request( '/affiliates/1/status', array( 'status'=>'active' ), 's2', array( 'affiliate_id'=>'1' ) ), 'status', 'affiliate.status', '/affiliates/{affiliate_id}/status' ); m5_assert( true === $status2['ok'] && 'active' === $status2['data']['status'], 'Status change and readback must succeed.' );
$m5_users[] = array( 'id'=>3, 'login'=>'reuse-user', 'email'=>'reuse@example.test' ); $m5_affiliates[4] = (object) array( 'affiliate_id'=>4, 'user_id'=>3, 'status'=>'active' ); $reuse = array_merge( $base, array( 'erp_kol_id'=>12, 'email'=>'reuse@example.test' ) ); $reuse_result = m5_dispatch( m5_request( '/affiliates/provision', $reuse, 'reuse-1' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( true === $reuse_result['ok'] && false === $reuse_result['data']['created_user'] && false === $reuse_result['data']['created_affiliate'], 'Exact-email user and existing affiliate must be reused.' ); $stable = m5_dispatch( m5_request( '/affiliates/provision', $reuse, 'reuse-2' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( $stable['data'] === $reuse_result['data'], 'Binding must remain stable across idempotency keys.' );
$m5_affiliates[4]->status = 'inactive'; $preserved = m5_dispatch( m5_request( '/affiliates/provision', $reuse, 'reuse-3' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( 'inactive' === $preserved['data']['affiliate_status'], 'Already-bound provision must preserve the current provider status.' );
$wpdb->bindings[] = array( 'connection_key'=>'site-a', 'erp_kol_id'=>99, 'wp_user_id'=>99, 'affiliate_id'=>1 ); $binding_conflict = m5_dispatch( m5_request( '/affiliates/provision', array_merge( $base, array( 'erp_kol_id'=>13 ) ), 'bind-conflict' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( 409 === $binding_conflict->get_status() && 'AFFILIATE_ID_CONFLICT' === $binding_conflict->get_data()['code'], 'Affiliate binding conflict must be 409.' );
$invalid_email = $base; $invalid_email['erp_kol_id'] = 15; $invalid_email['email'] = 'person@@example.test'; $invalid_email_result = m5_dispatch( m5_request( '/affiliates/provision', $invalid_email, 'invalid-email' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( 400 === $invalid_email_result->get_status(), 'Invalid raw email must be rejected without sanitizing into another address.' ); $invalid_status = m5_dispatch( m5_request( '/affiliates/1/status', array( 'status'=>'not-a-status' ), 'invalid-status', array( 'affiliate_id'=>'1' ) ), 'status', 'affiliate.status', '/affiliates/{affiliate_id}/status' ); m5_assert( 400 === $invalid_status->get_status(), 'Unknown status must be rejected.' );
$m5_users[] = array( 'id'=>4, 'login'=>'person-14', 'email'=>'occupied@example.test' ); $collision = array_merge( $base, array( 'erp_kol_id'=>14, 'email'=>'collision@example.test' ) ); $collision_result = m5_dispatch( m5_request( '/affiliates/provision', $collision, 'collision' ), 'provision', 'affiliate.provision', '/affiliates/provision' ); m5_assert( true === $collision_result['ok'] && 'person-14' !== $m5_users[4]['login'], 'Username collision must select a deterministic free candidate.' );
$notfound = m5_dispatch( m5_request( '/affiliates/999/status', array( 'status'=>'active' ), 's404', array( 'affiliate_id'=>'999' ) ), 'status', 'affiliate.status', '/affiliates/{affiliate_id}/status' ); m5_assert( 404 === $notfound->get_status(), 'Missing affiliate must return 404.' ); $notfound_retry = m5_dispatch( m5_request( '/affiliates/999/status', array( 'status'=>'active' ), 's404', array( 'affiliate_id'=>'999' ) ), 'status', 'affiliate.status', '/affiliates/{affiliate_id}/status' ); m5_assert( 404 === $notfound_retry->get_status(), 'Failed not-found replay must preserve 404.' );
$m5_provider = false; $unavailable = m5_dispatch( m5_request( '/affiliates/1/status', array( 'status'=>'active' ), 'unavailable', array( 'affiliate_id'=>'1' ) ), 'status', 'affiliate.status', '/affiliates/{affiliate_id}/status' ); m5_assert( 503 === $unavailable->get_status(), 'Unavailable provider must fail gracefully.' );
$serialized = serialize( $wpdb->rows ) . serialize( $wpdb->audit ); m5_assert( false === strpos( $serialized, 'PAY@Example.TEST' ) && false === strpos( $serialized, 'password' ), 'Password and payment email must not enter storage/audit.' ); echo "Connector M5 affiliate harness passed.\n";
