<?php
/** Executable M6 behavioral harness using in-memory WordPress/Woo/AffiliateWP stubs. */
define( 'ABSPATH', __DIR__ ); define( 'DAY_IN_SECONDS', 86400 ); define('ARRAY_A','ARRAY_A'); if ( ! defined( 'OPENSSL_RAW_DATA' ) ) { define('OPENSSL_RAW_DATA',1); } define('AUTH_KEY','a'); define('SECURE_AUTH_KEY','b'); define('LOGGED_IN_KEY','c'); define('NONCE_KEY','d');
if ( ! function_exists( 'openssl_encrypt' ) ) { function openssl_encrypt( $value, $cipher, $key, $options, $iv ) { return (string) $value; } function openssl_decrypt( $value, $cipher, $key, $options, $iv ) { return (string) $value; } }
function m6_assert( $ok, $message ) { if ( ! $ok ) { fwrite( STDERR, "FAIL: {$message}\n" ); exit( 1 ); } }
class WP_Error { private $c,$m,$d; function __construct($c,$m='',$d=array()){ $this->c=$c;$this->m=$m;$this->d=$d; } function get_error_code(){return $this->c;} function get_error_message(){return $this->m;} function get_error_data(){return $this->d;} }
function is_wp_error($v){return $v instanceof WP_Error;}
class WP_REST_Response { private $d,$s; function __construct($d,$s=200){$this->d=$d;$this->s=$s;} function get_data(){return $this->d;} function get_status(){return $this->s;} }
class M6_Request { private $h,$b,$r; function __construct($h,$b,$r){$this->h=$h;$this->b=$b;$this->r=$r;} function get_header($n){return $this->h[strtolower($n)]??'';} function get_json_params(){return json_decode($this->b,true);} function get_body(){return $this->b;} function get_route(){return $this->r;} function get_method(){return 'POST';} }
class M6_DB {
 public $prefix='wp_',$insert_id=0,$idempotency=array(),$bindings=array(),$audit=array(),$renew_noop=false,$finalize_zero=false;
 function prepare($q,...$a){if(false!==strpos($q,'lease_expires_at < UTC_TIMESTAMP()')){foreach($this->bindings as &$stale)if('processing'===$stale['state']&&!empty($stale['lease_expires_at'])&&strtotime($stale['lease_expires_at'].' UTC')<time()){$stale['lease_owner_hash']=$a[1]??'';$stale['lease_expires_at']=gmdate('Y-m-d H:i:s',time()+300);$q=str_replace('WHERE id = %d',"WHERE normalized_code = '".$stale['normalized_code']."'",$q);$q=str_replace('lease_expires_at < UTC_TIMESTAMP()','lease_expires_at >= UTC_TIMESTAMP()',$q);break;}}foreach($a as $v){$v=is_string($v)?"'".addslashes($v)."'":(is_null($v)?'NULL':(string)$v);$q=preg_replace('/%[sd]/',$v,$q,1);}return$q;}
 function insert($t,$d,$f=array()){if(false!==strpos($t,'idempotency')){foreach($this->idempotency as $r)if($r['mutation_identity_hash']===$d['mutation_identity_hash'])return false;$d['id']=++$this->insert_id;$this->idempotency[]=$d;return 1;}if(false!==strpos($t,'coupon_bindings')){foreach($this->bindings as $r)if($r['normalized_code']===$d['normalized_code'])return false;$d['id']=++$this->insert_id;$this->bindings[]=$d;return 1;}$this->audit[]=$d;return 1;}
 function get_row($q,$f=null){if(false!==strpos($q,'mutation_identity_hash')){preg_match("/mutation_identity_hash = '([^']+)'/",$q,$m);foreach($this->idempotency as $r)if(($m[1]??'')===$r['mutation_identity_hash'])return$r;}if(false!==strpos($q,'coupon_bindings')){preg_match("/normalized_code = '([^']+)'/",$q,$m);foreach($this->bindings as $r)if(($m[1]??'')===$r['normalized_code'])return$r;}if(preg_match('/WHERE id = (\d+)/',$q,$m))foreach($this->idempotency as $r)if((int)$r['id']===(int)$m[1])return$r;return null;}
 function update($t,$d,$w){foreach($this->idempotency as &$r)if((int)$r['id']===(int)$w['id']&&$r['state']===$w['state']){$r=array_merge($r,$d);return 1;}return 0;}
 function query($q){if(false!==strpos($q,'coupon_bindings')){preg_match("/normalized_code = '([^']+)'/",$q,$m);$n=$m[1]??'';preg_match("/lease_owner_hash = '([^']+)'/",$q,$m);$o=$m[1]??'';foreach($this->bindings as $i=>&$r){if($r['normalized_code']!==$n)continue;if(false!==strpos($q,'lease_expires_at >= UTC_TIMESTAMP()')){if($r['state']!=='processing'||$r['lease_owner_hash']!==$o||strtotime($r['lease_expires_at'].' UTC')<time())return 0;if($this->renew_noop)return 0;$r['lease_expires_at']=gmdate('Y-m-d H:i:s',time()+300);return 1;}if(false!==strpos($q,"state = 'processing'")&&false!==strpos($q,'state = \'ready\'')){if($this->finalize_zero)return 0;if($r['state']==='processing'&&$r['lease_owner_hash']===$o){$r['coupon_id']=preg_match('/coupon_id = (\d+)/',$q,$x)?(int)$x[1]:0;$r['affiliate_id']=preg_match('/affiliate_id = (\d+)/',$q,$x)?(int)$x[1]:0;$r['erp_kol_id']=preg_match('/erp_kol_id = (\d+)/',$q,$x)?(int)$x[1]:0;$r['state']='ready';$r['lease_owner_hash']=null;$r['lease_expires_at']=null;return 1;}}if(false!==strpos($q,'DELETE FROM')&&$r['state']==='processing'&&$r['lease_owner_hash']===$o){unset($this->bindings[$i]);$this->bindings=array_values($this->bindings);return 1;}}}if(preg_match('/WHERE id = (\d+)/',$q,$m))foreach($this->idempotency as &$r)if((int)$r['id']===(int)$m[1]&&$r['state']==='failed'&&!empty($r['retryable'])){$r['state']='processing';return 1;}return 0;}
 function get_results($q,$f=null){return$this->audit;}function get_var($q){return null;}function get_col($q=null){return array();}function get_charset_collate(){return '';}
}
class WooCommerce {}
class WC_Coupon { public $id=0,$code='',$type='percent',$amount='',$expiry=null,$meta=array(); function __construct($id=0){global$m6_coupons;if($id){if(!isset($m6_coupons[$id]))throw new Exception('missing');foreach($m6_coupons[$id] as $k=>$v)$this->$k=$v;}}function set_code($v){$this->code=$v;}function set_discount_type($v){$this->type=$v;}function set_amount($v){$this->amount=$v;}function set_date_expires($v){$this->expiry=$v;}function update_meta_data($k,$v){$this->meta[$k]=$v;}function save(){global$m6_coupons,$m6_coupon_writes,$m6_corrupt;if(!$this->id)$this->id=++$m6_coupon_writes;$this->code=strtolower(trim($this->code));$m6_coupons[$this->id]=array('id'=>$this->id,'code'=>$this->code,'type'=>$this->type,'amount'=>$this->amount,'expiry'=>$this->expiry,'meta'=>$this->meta);if($m6_corrupt)$m6_coupons[$this->id]['meta']['affwp_discount_affiliate']='999';}function delete($force=false){global$m6_coupons,$m6_coupon_deletes;++$m6_coupon_deletes;unset($m6_coupons[$this->id]);}function get_id(){return$this->id;}function get_code(){return$this->code;}function get_discount_type(){return$this->type;}function get_amount(){return$this->amount;}function get_date_expires(){return is_null($this->expiry)?null:new DateTimeImmutable('@'.$this->expiry);}}
$wpdb=new M6_DB();$m6_options=array();$m6_transients=array();$m6_coupons=array();$m6_coupon_writes=0;$m6_coupon_deletes=0;$m6_corrupt=false;$m6_affiliate_present=true;$m6_affiliates=array(7=>(object)array('affiliate_id'=>7,'user_id'=>70,'status'=>'active'));$m6_routes=array();
function get_option($k,$d=false){global$m6_options;return$m6_options[$k]??$d;}function add_option($k,$v){global$m6_options;$m6_options[$k]=$v;return true;}function update_option($k,$v){global$m6_options;$m6_options[$k]=$v;return true;}function get_transient($k){global$m6_transients;return$m6_transients[$k]??false;}function set_transient($k,$v,$ttl){global$m6_transients;$m6_transients[$k]=$v;return true;}function sanitize_text_field($v){return trim((string)$v);}function is_ssl(){return true;}function get_bloginfo(){return'6.0';}function register_rest_route($n,$p,$a){global$m6_routes;$m6_routes[$n.$p]=$a;}function wp_json_encode($v){return json_encode($v);}function absint($v){return abs((int)$v);}function home_url($p='/'){return'https://example.test'.$p;}function wp_generate_uuid4(){static $i=0;return'uuid-'.(++$i);}function get_post_meta($id,$key,$single=true){global$m6_coupons;return$m6_coupons[$id]['meta'][$key]??'';}function wc_strtolower($v){return strtolower($v);}function wc_format_decimal($v,$d=6,$trim=false){return(string)$v;}function wc_sanitize_coupon_code($v){return$v;}function wc_get_coupon_id_by_code($code){global$m6_coupons;$n=strtolower(trim($code));foreach($m6_coupons as $id=>$c)if(strtolower(trim($c['code']))===$n)return$id;return 0;}
function affiliate_wp(){global$m6_affiliate_present;return$m6_affiliate_present?(object)array():null;}function affwp_get_affiliate($id){global$m6_affiliates;return$m6_affiliates[(int)$id]??false;}function affwp_get_affiliate_statuses(){return array('active'=>'Active');}function affwp_set_affiliate_status(){return true;}
require_once dirname(__DIR__).'/inc/class-yby-database.php';require_once dirname(__DIR__).'/inc/class-yby-connector-idempotency.php';require_once dirname(__DIR__).'/inc/class-yby-connector-audit.php';require_once dirname(__DIR__).'/inc/class-yby-connector-coupon-bindings.php';require_once dirname(__DIR__).'/inc/class-yby-connector.php';
update_option(YBY_Connector::OPTION,array('enabled'=>true,'connection_key'=>'site-a','key_id'=>'erp-key'));$m6_secret=YBY_Connector::generate_secret();
function m6_request($route,$body,$key='',$connection='site-a',$omit=false){global$m6_secret;update_option(YBY_Connector::OPTION,array('enabled'=>true,'connection_key'=>$connection,'key_id'=>'erp-key'));$raw=json_encode($body);$ts=(string)time();$nonce='m6-'.$key.'-'.mt_rand(1000,9999);$h=array('x-yby-connection-key'=>$connection,'x-yby-key-id'=>'erp-key','x-yby-timestamp'=>$ts,'x-yby-nonce'=>$nonce,'x-yby-idempotency-key'=>$omit?'':$key,'x-yby-signature-version'=>'v1');$h['x-yby-signature']=YBY_Connector::sign('POST','/wp-json/andy-core/v1/erp'.$route,$ts,$nonce,$connection,$omit?'':$key,$raw,$m6_secret);return new M6_Request($h,$raw,'/wp-json/andy-core/v1/erp'.$route);}
function m6_call($r){return YBY_Connector::dispatch_coupon_provision($r);}function m6_d($r){global$m6_last;$m6_last=$r;return$r instanceof WP_REST_Response?$r->get_data():$r;}function m6_s($r){global$m6_last;$m6_last=$r;return$r instanceof WP_REST_Response?$r->get_status():200;}
$r=YBY_Connector::dispatch_coupon_check(m6_request('/coupons/check',array('code'=>'  SaveMe  '),'c1'));m6_assert(m6_s($r)===200&&m6_d($r)['data']['available']&&m6_d($r)['data']['normalized_code']==='saveme','check available and safe facts');$m6_coupons[41]=array('id'=>41,'code'=>'SAVECASE','type'=>'percent','amount'=>'10','expiry'=>null,'meta'=>array('affwp_discount_affiliate'=>'9'));$r=YBY_Connector::dispatch_coupon_check(m6_request('/coupons/check',array('code'=>' savecase '),'c2'));m6_assert(!m6_d($r)['data']['available']&&m6_d($r)['data']['coupon_id']===41,'case/whitespace conflict safe facts');
$body=array('erp_kol_id'=>11,'affiliate_id'=>7,'code'=>'  Spring10  ','discount_type'=>'percent','amount'=>'10.00','expiry'=>'2030-02-28T10:00:00+08:00');$bad_date=array_merge($body,array('code'=>'BadDate','expiry'=>'2030-02-31T10:00:00+08:00'));$r=m6_call(m6_request('/coupons/provision',$bad_date,'bad-date'));m6_assert(m6_s($r)===400&&0===$m6_coupon_writes,'impossible ISO date rejected before provider write');$r=m6_call(m6_request('/coupons/provision',$body,'', 'site-a',true));m6_assert(m6_s($r)===400,'missing idempotency rejected');$r=m6_call(m6_request('/coupons/provision',$body,'p1'));$d=m6_d($r);m6_assert(m6_s($r)===200&&$d['data']['coupon_id']===1&&$m6_coupon_writes===1&&$wpdb->bindings[0]['affiliate_id']===7&&$wpdb->bindings[0]['erp_kol_id']===11,'first provision creates exactly one coupon and exact binding');$writes=$m6_coupon_writes;$r2=m6_call(m6_request('/coupons/provision',$body,'p1'));m6_assert(m6_d($r2)['data']===$d['data']&&$m6_coupon_writes===$writes,'same key retry identical and no provider writes');$changed=$body;$changed['amount']='11';$r=m6_call(m6_request('/coupons/provision',$changed,'p1'));m6_assert(m6_s($r)===409&&m6_d($r)['code']==='IDEMPOTENCY_CONFLICT','changed body same key conflict');$case_variant=$body;$case_variant['code']='SPRING10';$r=m6_call(m6_request('/coupons/provision',$case_variant,'p2'));m6_assert(m6_s($r)===409&&m6_d($r)['code']==='COUPON_CONFLICT'&&$m6_coupon_writes===$writes,'different key case-variant normalized code conflict');$r=m6_call(m6_request('/coupons/provision',$body,'p3','site-b'));m6_assert(m6_s($r)===409&&m6_d($r)['code']==='COUPON_CONFLICT','global conflict across connection key');
$owner=hash('sha256','owner');YBY_Connector_Coupon_Bindings::reserve('site-a','stale','Stale',$owner);foreach($wpdb->bindings as &$x)if($x['normalized_code']==='stale')$x['lease_expires_at']=gmdate('Y-m-d H:i:s',time()-10);$r=YBY_Connector_Coupon_Bindings::reserve('site-b','stale','Stale2','new');m6_assert($r['status']==='acquired'&&!empty($r['recovered']),'stale reservation recovery');YBY_Connector_Coupon_Bindings::reserve('site-a','renew','Renew',$owner);$wpdb->renew_noop=true;m6_assert(YBY_Connector_Coupon_Bindings::renew('renew',$owner),'same-second no-op renew succeeds after readback');m6_assert(!YBY_Connector_Coupon_Bindings::renew('renew','wrong'),'wrong owner renew false');foreach($wpdb->bindings as &$x)if($x['normalized_code']==='renew')$x['lease_expires_at']=gmdate('Y-m-d H:i:s',time()-10);m6_assert(!YBY_Connector_Coupon_Bindings::renew('renew',$owner),'expired renew false');
$m6_affiliate_present=false;$r=m6_call(m6_request('/coupons/provision',array_merge($body,array('code'=>'Absent')),'absent'));m6_assert(m6_s($r)===503,'provider absence');$m6_affiliate_present=true;$r=m6_call(m6_request('/coupons/provision',array_merge($body,array('affiliate_id'=>999,'code'=>'MissingAff')),'missing-aff'));m6_assert(m6_s($r)===404&&m6_d($r)['code']==='AFFILIATE_NOT_FOUND','exact missing Affiliate 404');$r=m6_call(m6_request('/coupons/provision',array_merge($body,array('code'=>'SAVECASE')),'existing'));m6_assert(m6_s($r)===409&&$m6_coupons[41]['meta']['affwp_discount_affiliate']==='9','pre-existing coupon never reassigned');$r2=m6_call(m6_request('/coupons/provision',array_merge($body,array('code'=>'SAVECASE')),'existing'));m6_assert(m6_s($r2)===409&&m6_d($r2)['code']==='COUPON_CONFLICT','failed coupon conflict replay preserves 409');
$wpdb->bindings=array();$m6_corrupt=true;$r=m6_call(m6_request('/coupons/provision',array_merge($body,array('erp_kol_id'=>12,'code'=>'Mismatch')),'mismatch'));m6_assert(m6_s($r)===503&&$m6_coupon_deletes===1&&!isset($m6_coupons[43])&&isset($m6_coupons[41]),'readback mismatch safely compensates exact new coupon only');m6_assert(strpos(serialize($wpdb->audit).serialize($wpdb->idempotency),'password')===false&&strpos(serialize($wpdb->audit).serialize($wpdb->idempotency),'coupon_id')!==false,'audit/idempotency safe fields');YBY_Connector::register_routes();m6_assert(count($m6_routes)===12&&isset($m6_routes['andy-core/v1/erp/affiliates/check'])&&isset($m6_routes['andy-core/v1/erp/payouts/complete']),'KOL create contract route surface');echo "Connector M6 coupon behavioral harness passed.\n";
