<?php
/** Focused ERP Connector WordPress password mutation harness. */
define( 'ABSPATH', __DIR__ ); define( 'ARRAY_A', 'ARRAY_A' ); define( 'AFFILIATEWP_VERSION', '2.35.0' );
define( 'AUTH_KEY', 'a' ); define( 'SECURE_AUTH_KEY', 'b' ); define( 'LOGGED_IN_KEY', 'c' ); define( 'NONCE_KEY', 'd' );
if ( ! function_exists( 'openssl_encrypt' ) ) { define( 'OPENSSL_RAW_DATA', 1 ); function openssl_encrypt( $data, $cipher, $key, $options, $iv ) { return (string) $data; } function openssl_decrypt( $data, $cipher, $key, $options, $iv ) { return (string) $data; } }
$options = array(); $transients = array(); $routes = array(); $users = array( 41 => (object) array( 'ID' => 41, 'user_pass' => 'old-hash' ) ); $affiliates = array( 77 => (object) array( 'affiliate_id' => 77, 'user_id' => 41 ) ); $writes = 0; $password_provider = true;
function get_option( $k, $d = false ) { global $options; return array_key_exists( $k, $options ) ? $options[ $k ] : $d; } function add_option( $k, $v, $x = '', $a = true ) { global $options; $options[ $k ] = $v; return true; } function update_option( $k, $v, $a = null ) { global $options; $options[ $k ] = $v; return true; }
function get_transient( $k ) { global $transients; return $transients[ $k ] ?? false; } function set_transient( $k, $v, $t ) { global $transients; $transients[ $k ] = $v; return true; } function is_ssl() { return true; } function get_bloginfo( $x = '' ) { return '7.1'; } function register_rest_route( $n, $r, $a ) { global $routes; $routes[ $n . $r ] = $a; } function wp_json_encode( $v ) { return json_encode( $v ); } function home_url( $p = '/' ) { return 'https://example.test' . $p; } function sanitize_text_field( $v ) { return trim( strip_tags( (string) $v ) ); } function is_wp_error( $v ) { return $v instanceof WP_Error; } function absint( $v ) { return abs( (int) $v ); }
class WP_Error { public $code, $message, $data; function __construct( $c, $m = '', $d = array() ) { $this->code = $c; $this->message = $m; $this->data = $d; } function get_error_code() { return $this->code; } function get_error_message() { return $this->message; } function get_error_data() { return $this->data; } }
class WP_REST_Response { public $data, $status; function __construct( $d, $s = 200 ) { $this->data = $d; $this->status = $s; } function get_data() { return $this->data; } function get_status() { return $this->status; } }
class Password_Request { public $headers, $body, $route, $params; function __construct( $h, $b, $p = array() ) { $this->headers = $h; $this->body = $b; $this->route = '/wp-json/andy-core/v1/erp/wordpress/users/' . ( $p['user_id'] ?? 41 ) . '/password'; $this->params = $p; } function get_header( $n ) { foreach ( $this->headers as $k => $v ) if ( strtolower( $k ) === strtolower( $n ) ) return $v; return ''; } function get_json_params() { return json_decode( $this->body, true ); } function get_body() { return $this->body; } function get_method() { return 'POST'; } function get_route() { return $this->route; } function get_param( $k ) { return $this->params[ $k ] ?? null; } }
class Password_DB { public $prefix = 'wp_', $insert_id = 0, $idempotency = array(), $audit = array(), $bindings = array(); function prepare( $q, ...$a ) { foreach ( $a as $v ) { $q = preg_replace( '/%[sd]/', is_string( $v ) ? "'" . $v . "'" : $v, $q, 1 ); } return $q; } function insert( $t, $d, $f = array() ) { if ( strpos( $t, 'idempotency' ) !== false ) { foreach ( $this->idempotency as $r ) if ( $r['mutation_identity_hash'] === $d['mutation_identity_hash'] ) return false; $d['id'] = ++$this->insert_id; $this->idempotency[] = $d; return 1; } if ( strpos( $t, 'audit' ) !== false ) { $d['id'] = ++$this->insert_id; $this->audit[] = $d; return 1; } return false; } function get_row( $q, $f = null ) { if ( strpos( $q, 'idempotency' ) !== false ) { foreach ( $this->idempotency as $r ) if ( strpos( $q, "mutation_identity_hash = '" . $r['mutation_identity_hash'] . "'" ) !== false || ( preg_match( '/WHERE id = (\d+)/', $q, $m ) && (int) $r['id'] === (int) $m[1] ) ) return $r; } if ( strpos( $q, 'affiliate_bindings' ) !== false && preg_match( "/connection_key = '([^']+)' AND erp_kol_id = (\d+)/", $q, $m ) ) foreach ( $this->bindings as $r ) if ( (string) $r['connection_key'] === $m[1] && (int) $r['erp_kol_id'] === (int) $m[2] ) return $r; return null; } function update( $t, $d, $w ) { foreach ( $this->idempotency as &$r ) if ( (int) $r['id'] === (int) $w['id'] && $r['state'] === $w['state'] ) { $r = array_merge( $r, $d ); return 1; } return 0; } function query( $q ) { foreach ( $this->idempotency as &$r ) if ( preg_match( '/WHERE id = (\d+)/', $q, $m ) && (int) $r['id'] === (int) $m[1] && 'failed' === $r['state'] ) { $r['state'] = 'processing'; return 1; } return 0; } }
$wpdb = new Password_DB(); $wpdb->bindings[] = array( 'connection_key' => 'site-a', 'erp_kol_id' => 9, 'wp_user_id' => 41, 'affiliate_id' => 77, 'state' => 'ready' );
function get_user_by( $field, $value ) { global $users; return 'id' === $field && isset( $users[(int) $value ] ) ? $users[(int) $value ] : false; } function wp_update_user( $data ) { global $users, $writes; ++$writes; $users[(int) $data['ID']]->user_pass = 'hash:' . $data['user_pass']; return (int) $data['ID']; } function wp_check_password( $password, $hash, $user_id = '' ) { return hash_equals( 'hash:' . $password, (string) $hash ); } function affwp_get_affiliate( $id ) { global $affiliates; return $affiliates[(int) $id] ?? false; } function affiliate_wp() { global $password_provider; return $password_provider ? (object) array() : false; }
require_once dirname( __DIR__ ) . '/inc/class-yby-database.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector-idempotency.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector-audit.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector-affiliate-bindings.php'; require_once dirname( __DIR__ ) . '/inc/class-yby-connector.php';
function password_assert( $ok, $msg ) { if ( ! $ok ) { fwrite( STDERR, "FAIL: {$msg}\n" ); exit( 1 ); } } function password_status( $r ) { return $r instanceof WP_REST_Response ? $r->get_status() : 200; } function password_data( $r ) { return $r instanceof WP_REST_Response ? $r->get_data() : $r; }
YBY_Connector::save( array( 'enabled' => true, 'connection_key' => 'site-a', 'key_id' => 'erp-key' ) ); $secret = YBY_Connector::generate_secret();
function password_request( $body, $key = 'pw-key', $user_id = 41 ) { global $secret; $raw = json_encode( $body ); $ts = (string) time(); $nonce = 'pw-' . $key . '-' . mt_rand( 1000, 9999 ); $h = array( 'X-YBY-Connection-Key' => 'site-a', 'X-YBY-Key-Id' => 'erp-key', 'X-YBY-Timestamp' => $ts, 'X-YBY-Nonce' => $nonce, 'X-YBY-Idempotency-Key' => $key, 'X-YBY-Signature-Version' => 'v1' ); $h['X-YBY-Signature'] = YBY_Connector::sign( 'POST', '/wp-json/andy-core/v1/erp/wordpress/users/' . $user_id . '/password', $ts, $nonce, 'site-a', $key, $raw, $secret ); return new Password_Request( $h, $raw, array( 'user_id' => $user_id ) ); }
$body = array( 'erp_kol_id' => 9, 'affiliate_id' => 77, 'password' => 'NewPassword123' ); $first = YBY_Connector::dispatch_wordpress_password( password_request( $body ) ); password_assert( 200 === password_status( $first ) && array( 'wordpress_user_id' => 41, 'affiliate_id' => 77, 'password_updated' => true ) === password_data( $first )['data'] && 1 === $writes, 'valid exact update and readback' ); $replay = YBY_Connector::dispatch_wordpress_password( password_request( $body ) ); password_assert( 200 === password_status( $replay ) && 1 === $writes, 'replay must not mutate twice' ); $changed = $body; $changed['password'] = 'ChangedPassword123'; $conflict = YBY_Connector::dispatch_wordpress_password( password_request( $changed ) ); password_assert( 409 === password_status( $conflict ), 'changed password must conflict on same idempotency key' );
$invalid = $body; $invalid['password'] = 'short1'; password_assert( 400 === password_status( YBY_Connector::dispatch_wordpress_password( password_request( $invalid, 'invalid' ) ) ), 'invalid password rejected' ); $wpdb->bindings[0]['affiliate_id'] = 78; password_assert( 409 === password_status( YBY_Connector::dispatch_wordpress_password( password_request( $body, 'binding' ) ) ) && 1 === $writes, 'binding mismatch rejected before write' ); $wpdb->bindings[0]['affiliate_id'] = 77; $affiliates[77]->user_id = 42; $provider_mismatch = YBY_Connector::dispatch_wordpress_password( password_request( $body, 'provider' ) ); password_assert( 409 === password_status( $provider_mismatch ) && 1 === $writes, 'provider identity mismatch rejected before write' ); $provider_mismatch_replay = YBY_Connector::dispatch_wordpress_password( password_request( $body, 'provider' ) ); password_assert( 409 === password_status( $provider_mismatch_replay ), 'provider identity mismatch replay must remain 409' ); $affiliates[77]->user_id = 41;
$wpdb->bindings[] = array( 'connection_key' => 'site-a', 'erp_kol_id' => 10, 'wp_user_id' => 42, 'affiliate_id' => 78, 'state' => 'ready' ); $affiliates[78] = (object) array( 'affiliate_id' => 78, 'user_id' => 42 ); $not_found_body = array( 'erp_kol_id' => 10, 'affiliate_id' => 78, 'password' => $body['password'] ); $not_found_first = YBY_Connector::dispatch_wordpress_password( password_request( $not_found_body, 'not-found', 42 ) ); $not_found_replay = YBY_Connector::dispatch_wordpress_password( password_request( $not_found_body, 'not-found', 42 ) ); password_assert( 404 === password_status( $not_found_first ) && 404 === password_status( $not_found_replay ), 'missing WordPress user must replay as 404' ); $password_provider = false; $unavailable_first = YBY_Connector::dispatch_wordpress_password( password_request( $body, 'unavailable' ) ); $unavailable_replay = YBY_Connector::dispatch_wordpress_password( password_request( $body, 'unavailable' ) ); password_assert( 503 === password_status( $unavailable_first ) && 503 === password_status( $unavailable_replay ), 'provider failure must remain 503 on retry' ); $password_provider = true;
YBY_Connector::register_routes(); password_assert( isset( $routes['andy-core/v1/erp/wordpress/users/(?P<user_id>\\d+)/password'] ) && 'POST' === $routes['andy-core/v1/erp/wordpress/users/(?P<user_id>\\d+)/password']['methods'], 'password route registered as POST' ); $statuses = YBY_Connector::endpoint_statuses(); password_assert( 13 === count( $statuses ) && isset( $statuses['wordpress_password'] ) && 'POST' === $statuses['wordpress_password']['method'], 'password endpoint status row registered' ); $stored = serialize( $wpdb->audit ) . serialize( $wpdb->idempotency ) . serialize( password_data( $first ) ); password_assert( false === strpos( $stored, 'NewPassword123' ) && false === strpos( $stored, 'user_pass' ), 'password absent from audit/idempotency/result' ); echo "Connector WordPress password harness passed.\n";
