<?php
/** Executable M7 payout contract harness using production Connector classes and in-memory doubles. */
define( 'ABSPATH', __DIR__ ); define( 'ARRAY_A', 'ARRAY_A' ); define( 'AFFILIATEWP_VERSION', '2.35.0' );
define( 'AUTH_KEY', 'a' ); define( 'SECURE_AUTH_KEY', 'b' ); define( 'LOGGED_IN_KEY', 'c' ); define( 'NONCE_KEY', 'd' );
$options = array(); $transients = array(); $routes = array(); $payouts = array(); $referrals = array( 10 => (object) array( 'referral_id'=>10, 'affiliate_id'=>7, 'amount'=>'4.25', 'currency'=>'USD', 'status'=>'unpaid', 'payout_id'=>0 ), 11 => (object) array( 'referral_id'=>11, 'affiliate_id'=>7, 'amount'=>'5.75', 'currency'=>'USD', 'status'=>'unpaid', 'payout_id'=>0 ) ); $provider = true; $creates = 0;
function get_option( $k, $d = false ) { global $options; return array_key_exists( $k, $options ) ? $options[ $k ] : $d; } function add_option( $k, $v, $x='', $a=true ) { global $options; $options[$k]=$v; return true; } function update_option( $k, $v, $a=null ) { global $options; $options[$k]=$v; return true; }
function get_transient( $k ) { global $transients; return $transients[$k] ?? false; } function set_transient( $k, $v, $t ) { global $transients; $transients[$k]=$v; return true; } function is_ssl(){return true;} function home_url($p='/'){return 'https://example.test'.$p;} function get_bloginfo($x=''){return '7.1';} function register_rest_route($n,$r,$a){global $routes;$routes[$n.$r]=$a;} function wp_json_encode($v){return json_encode($v);} function absint($v){return abs((int)$v);} function sanitize_text_field($v){return trim(strip_tags((string)$v));} function wp_strip_all_tags($v){return strip_tags((string)$v);} function is_email($v){return false!==filter_var($v,FILTER_VALIDATE_EMAIL);} function is_wp_error($v){return $v instanceof WP_Error;}
class WP_Error { public $code,$message,$data; function __construct($c,$m='',$d=array()){ $this->code=$c;$this->message=$m;$this->data=$d;} function get_error_code(){return $this->code;} function get_error_message(){return $this->message;} function get_error_data(){return $this->data;} }
class WP_REST_Response { public $data,$status; function __construct($d,$s=200){$this->data=$d;$this->status=$s;} function get_data(){return $this->data;} function get_status(){return $this->status;} }
class M7_Request { public $headers,$body,$route; function __construct($h,$b,$r='/wp-json/andy-core/v1/erp/payouts/complete'){ $this->headers=$h;$this->body=$b;$this->route=$r;} function get_header($n){foreach($this->headers as $k=>$v)if(strtolower($k)===strtolower($n))return $v;return '';} function get_json_params(){return json_decode($this->body,true);} function get_body(){return $this->body;} function get_method(){return 'POST';} function get_route(){return $this->route;} }
class M7_DB {
	public $prefix = 'wp_', $insert_id = 0, $bindings = array(), $claims = array(), $audit = array(), $idempotency = array();

	function prepare( $q, ...$a ) { foreach ( $a as $v ) { $v = is_string( $v ) ? "'" . $v . "'" : $v; $q = preg_replace( '/%[sd]/', $v, $q, 1 ); } return $q; }
	function insert( $t, $d, $f = array() ) {
		if ( strpos( $t, 'idempotency' ) !== false ) { foreach ( $this->idempotency as $r ) if ( $r['mutation_identity_hash'] === $d['mutation_identity_hash'] ) return false; $d['id'] = ++$this->insert_id; $this->idempotency[] = $d; return 1; }
		if ( strpos( $t, 'payout_bindings' ) !== false ) { foreach ( $this->bindings as $r ) if ( $r['connection_key'] === $d['connection_key'] && $r['erp_payout_request_id'] === $d['erp_payout_request_id'] ) return false; $d['id'] = ++$this->insert_id; $this->bindings[] = $d; return 1; }
		if ( strpos( $t, 'payout_claims' ) !== false ) { foreach ( $this->claims as $r ) if ( (int) $r['referral_id'] === (int) $d['referral_id'] ) return false; $d['id'] = ++$this->insert_id; $this->claims[] = $d; return 1; }
		$this->audit[] = $d; return 1;
	}
	function get_row( $q, $f = null ) {
		if ( strpos( $q, 'idempotency' ) !== false ) { preg_match( '/mutation_identity_hash = (\S+)/', $q, $m ); foreach ( $this->idempotency as $r ) if ( $r['mutation_identity_hash'] === trim( $m[1] ?? '', "'\"" ) ) return $r; if ( preg_match( '/WHERE id = (\d+)/', $q, $m ) ) foreach ( $this->idempotency as $r ) if ( (int) $r['id'] === (int) $m[1] ) return $r; }
		if ( strpos( $q, 'payout_bindings' ) !== false ) { foreach ( $this->bindings as $r ) if ( $this->binding_matches( $q, $r ) ) return $r; }
		if ( strpos( $q, 'payout_claims' ) !== false ) { preg_match( '/referral_id = (\d+)/', $q, $m ); foreach ( $this->claims as $r ) if ( (int) $r['referral_id'] === (int) ( $m[1] ?? 0 ) ) return $r; }
		return null;
	}
	function update( $t, $d, $w, $f = array(), $wf = array() ) { foreach ( $this->idempotency as &$r ) if ( (int) $r['id'] === (int) ( $w['id'] ?? 0 ) && $r['state'] === $w['state'] ) { $r = array_merge( $r, $d ); return 1; } return 0; }
	function query( $q ) {
		if ( strpos( $q, 'idempotency' ) !== false ) { if ( ! preg_match( '/WHERE id = (\d+)/', $q, $m ) ) return 0; foreach ( $this->idempotency as &$r ) if ( (int) $r['id'] === (int) $m[1] && 'failed' === $r['state'] ) { $r['state'] = 'processing'; return 1; } return 0; }
		if ( strpos( $q, 'payout_bindings' ) === false ) return 0;
		foreach ( $this->bindings as &$r ) {
			if ( ! $this->binding_matches( $q, $r ) || ! $this->binding_predicates_match( $q, $r ) ) continue;
			if ( preg_match( "/SET .*lease_owner_hash = '([^']+)'/", $q, $m ) ) $r['lease_owner_hash'] = $m[1]; elseif ( strpos( $q, 'SET lease_owner_hash = NULL' ) !== false ) $r['lease_owner_hash'] = null;
			if ( preg_match( "/lease_expires_at = '([^']+)'/", $q, $m ) ) $r['lease_expires_at'] = $m[1]; elseif ( strpos( $q, 'lease_expires_at = NULL' ) !== false ) $r['lease_expires_at'] = null;
			if ( preg_match( "/SET state = '([^']+)'|, state = '([^']+)'/", $q, $m ) ) $r['state'] = $m[1] ?: $m[2];
			if ( preg_match( '/payout_id = (\d+)/', $q, $m ) ) $r['payout_id'] = (int) $m[1];
			return 1;
		}
		return 0;
	}
	private function binding_matches( $q, $r ) {
		if ( preg_match( '/WHERE id = (\d+)/', $q, $m ) ) return (int) $r['id'] === (int) $m[1];
		preg_match( "/connection_key = '([^']+)'/", $q, $connection ); preg_match( "/erp_payout_request_id = '([^']+)'/", $q, $request );
		return isset( $connection[1], $request[1] ) && $r['connection_key'] === $connection[1] && $r['erp_payout_request_id'] === $request[1];
	}
	private function binding_predicates_match( $q, $r ) {
		$where = strstr( $q, ' WHERE ' ); $where = false === $where ? '' : $where;
		if ( preg_match( "/state = '([^']+)'/", $where, $m ) && $r['state'] !== $m[1] && strpos( $where, "state IN ('processing','provider_created')" ) === false ) return false;
		if ( strpos( $where, "state IN ('processing','provider_created')" ) !== false && ! in_array( $r['state'], array( 'processing', 'provider_created' ), true ) ) return false;
		if ( preg_match( "/lease_owner_hash = '([^']+)'/", $where, $m ) && (string) $r['lease_owner_hash'] !== $m[1] ) return false;
		if ( preg_match( '/payout_id = (\d+)/', $where, $m ) && (int) $r['payout_id'] !== (int) $m[1] ) return false;
		if ( strpos( $where, 'lease_expires_at >= UTC_TIMESTAMP()' ) !== false && ( empty( $r['lease_expires_at'] ) || strtotime( $r['lease_expires_at'] . ' UTC' ) < time() ) ) return false;
		if ( strpos( $where, 'lease_expires_at < UTC_TIMESTAMP() OR lease_expires_at IS NULL' ) !== false && ! empty( $r['lease_expires_at'] ) && strtotime( $r['lease_expires_at'] . ' UTC' ) >= time() ) return false;
		return true;
	}
	function get_charset_collate() { return ''; }
}
$wpdb = new M7_DB();
function affwp_get_affiliate($id){global $provider;return $provider&&7===(int)$id?(object)array('affiliate_id'=>7,'status'=>'active'):false;} function affwp_get_referral($id){global $provider,$referrals;return $provider&&isset($referrals[(int)$id])?$referrals[(int)$id]:false;}
function affwp_add_payout($a){global $payouts,$referrals,$creates; $id=++$creates;$date=(new DateTimeImmutable($a['date'].' 12:00:00',new DateTimeZone('America/Los_Angeles')))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$payouts[$id]=(object)array('payout_id'=>$id,'affiliate_id'=>$a['affiliate_id'],'referrals'=>$a['referrals'],'amount'=>$a['amount'],'payout_method'=>$a['payout_method'],'status'=>$a['status'],'date'=>$date); foreach($a['referrals'] as $r){$referrals[$r]->payout_id=$id;$referrals[$r]->status='paid';}return $id;}
function affwp_get_payout($id){global $payouts;return $payouts[(int)$id]??false;} function affwp_get_payout_referrals($p){global $referrals;$out=array();foreach((array)$p->referrals as $id)$out[]=$referrals[$id];return $out;} function affwp_set_referral_status($id,$status){global $referrals;if(isset($referrals[$id])){$referrals[$id]->status=$status;return true;}return false;}
class M7_Referrals { public function update($id,$data,$where='',$context=''){global $referrals;if(isset($referrals[$id])&&'referral'===$context){foreach($data as $k=>$v)$referrals[$id]->{$k}=$v;return true;}return false;} public function get($id){return affwp_get_referral($id);} }
class M7_Payouts { public function get($id){return affwp_get_payout($id);} public function get_payouts($args){global $payouts;$out=array();foreach($payouts as $payout){if((int)($args['affiliate_id']??0)!==(int)$payout->affiliate_id||($args['payout_method']??'')!==$payout->payout_method||($args['status']??'')!==$payout->status||substr(get_date_from_gmt($payout->date,'Y-m-d H:i:s'),0,10)!==($args['date']??''))continue;$out[]=$payout;}return $out;} public function get_payout_ids_by_referrals($ids){global $referrals;$out=array();foreach($ids as $id)if(!empty($referrals[$id]->payout_id))$out[]=(int)$referrals[$id]->payout_id;return array_values(array_unique($out));} }
function affiliate_wp(){return (object)array('referrals'=>new M7_Referrals(),'affiliates'=>(object)array('payouts'=>new M7_Payouts()));} function get_date_from_gmt($date,$format='Y-m-d H:i:s'){if('2030-03-01 20:00:00'===$date)return '2030-02-28 20:00:00';return (new DateTimeImmutable($date,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('America/Los_Angeles'))->format($format);}
require_once dirname(__DIR__).'/inc/class-yby-database.php'; require_once dirname(__DIR__).'/inc/class-yby-connector-idempotency.php'; require_once dirname(__DIR__).'/inc/class-yby-connector-audit.php'; require_once dirname(__DIR__).'/inc/class-yby-connector-payout-bindings.php'; require_once dirname(__DIR__).'/inc/class-yby-connector.php';
function m7_assert($ok,$msg){if(!$ok){fwrite(STDERR,"FAIL: $msg\n");exit(1);}} function m7_status($r){return $r instanceof WP_REST_Response?$r->get_status():200;} function m7_data($r){return $r instanceof WP_REST_Response?$r->get_data():$r;} function m7_body($extra=array()){return array_merge(array('erp_payout_request_id'=>9001,'affiliate_id'=>7,'referral_ids'=>array(11,10),'amount'=>'10.00','currency'=>'USD','payout_method'=>'paypal_manual','paypal_transaction_id'=>'txn-secret-never-stored','paid_at'=>'2030-02-28'),$extra);} function m7_req($body,$key='k1'){global $secret;$raw=json_encode($body);$ts=(string)time();$nonce='m7-'.$key.'-'.mt_rand(1000,9999);$h=array('X-YBY-Connection-Key'=>'site-a','X-YBY-Key-Id'=>'erp-key','X-YBY-Timestamp'=>$ts,'X-YBY-Nonce'=>$nonce,'X-YBY-Idempotency-Key'=>$key,'X-YBY-Signature-Version'=>'v1');$h['X-YBY-Signature']=YBY_Connector::sign('POST','/wp-json/andy-core/v1/erp/payouts/complete',$ts,$nonce,'site-a',$key,$raw,$secret);return new M7_Request($h,$raw);}
YBY_Connector::save(array('enabled'=>true,'connection_key'=>'site-a','key_id'=>'erp-key'));$secret=YBY_Connector::generate_secret(); m7_assert(is_string($secret),'secret setup');
$missing=m7_req(m7_body(),''); $missing->headers['X-YBY-Signature']=YBY_Connector::sign('POST',$missing->get_route(),$missing->headers['X-YBY-Timestamp'],$missing->headers['X-YBY-Nonce'],'site-a','',$missing->body,$secret);m7_assert(400===m7_status(YBY_Connector::dispatch_payout_complete($missing)),'missing idempotency');
$first=YBY_Connector::dispatch_payout_complete(m7_req(m7_body()));m7_assert(200===m7_status($first)&&1===m7_data($first)['data']['payout_id']&&1===$creates&&array(10,11)===m7_data($first)['data']['referral_ids'],'exact first payout and canonical order');$replay=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(),'k1'));m7_assert(200===m7_status($replay)&&1===$creates,'same-key replay');$other=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(),'k2'));m7_assert(200===m7_status($other)&&1===$creates,'different key same ERP identity');$conf=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('amount'=>'9.99')),'k3'));m7_assert(409===m7_status($conf)&&'PAYOUT_IDEMPOTENCY_CONFLICT'===m7_data($conf)['code'],'ERP fingerprint conflict');
$validation_case_index=0;foreach(array(array('affiliate_id'=>999,'code'=>'AFFILIATE_NOT_FOUND'),array('referral_ids'=>array(10,10),'code'=>'VALIDATION_FAILED'),array('currency'=>'EUR','code'=>'REFERRAL_NOT_ELIGIBLE'),array('amount'=>'1.00','code'=>'VALIDATION_FAILED'),array('paid_at'=>'2030-02-30','code'=>'VALIDATION_FAILED'),array('payout_method'=>'paypal','code'=>'VALIDATION_FAILED')) as $case){global $referrals,$payouts;$validation_case_index++;$saved_first_payout=$payouts[1]??null;unset($payouts[1]);foreach($referrals as $ref){$ref->status='unpaid';$ref->payout_id=0;}$expected=$case['code'];unset($case['code']);$r=YBY_Connector::dispatch_payout_complete(m7_req(array_merge(m7_body(array('erp_payout_request_id'=>9500+$validation_case_index)),$case),'v'.$validation_case_index));if($saved_first_payout){$payouts[1]=$saved_first_payout;}m7_assert(m7_data($r)['code']===$expected,'validation/provider stable code expected '.$expected.' got '.(m7_data($r)['code']??''));}
$wpdb->claims=array();m7_assert(true===YBY_Connector_Payout_Bindings::claim('site-a','9002',10),'claim first');m7_assert(false===YBY_Connector_Payout_Bindings::claim('site-b','9003',10),'overlap claim blocked');$lease=YBY_Connector_Payout_Bindings::reserve('site-a','9010','f',hash('sha256','o'));m7_assert(is_array($lease)&&'acquired'===$lease['status']&&true===YBY_Connector_Payout_Bindings::renew('site-a','9010',hash('sha256','o')),'lease renew');m7_assert(false===YBY_Connector_Payout_Bindings::renew('site-a','9010',hash('sha256','wrong')),'wrong owner lease');
$same_erp_diff_key=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9001)),'k9'));m7_assert(200===m7_status($same_erp_diff_key)&&1===$creates,'different key reuses durable payout');
$different_erp_same_key=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9011)),'k1'));m7_assert(409===m7_status($different_erp_same_key)&&'IDEMPOTENCY_CONFLICT'===m7_data($different_erp_same_key)['code']&&1===$creates,'same key different valid ERP request conflicts before provider create');
$payouts[1]->date='2030-03-03 20:00:00';$referrals[12]=(object)array('referral_id'=>12,'affiliate_id'=>7,'amount'=>'4.25','currency'=>'USD','status'=>'paid','payout_id'=>2);$referrals[13]=(object)array('referral_id'=>13,'affiliate_id'=>7,'amount'=>'5.75','currency'=>'USD','status'=>'paid','payout_id'=>2);$payouts[2]=(object)array('payout_id'=>2,'affiliate_id'=>7,'referrals'=>array(12,13),'amount'=>'10.00','payout_method'=>'manual','status'=>'paid','date'=>'2030-03-01 20:00:00');$before_crash_creates=$creates;$crash=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9012,'referral_ids'=>array(12,13))),'crash'));m7_assert(200===m7_status($crash)&&$before_crash_creates===$creates,'crash recovery adopts exact provider payout without second create');
$lease_input=array('connection_key'=>'site-a','erp_payout_request_id'=>9013,'affiliate_id'=>7,'referral_ids'=>array(12,13),'amount'=>'10','currency'=>'USD','payout_method'=>'paypal_manual','paypal_transaction_id'=>'txn-secret-never-stored','paid_at'=>'2030-02-28');$wpdb->bindings[]=array('id'=>999,'connection_key'=>'site-a','erp_payout_request_id'=>'9013','request_fingerprint'=>YBY_Connector_Idempotency::fingerprint($lease_input), 'state'=>'provider_created','payout_id'=>2,'lease_owner_hash'=>'old','lease_expires_at'=>'2000-01-01 00:00:00');$lease_retry=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9013,'referral_ids'=>array(12,13))),'lease-retry'));m7_assert(200===m7_status($lease_retry)&&'ready'===$wpdb->bindings[count($wpdb->bindings)-1]['state'],'provider_created retry reacquires stale lease and finalizes ready');$payouts[2]->date='2030-03-02 20:00:00';
$referrals[14]=(object)array('referral_id'=>14,'affiliate_id'=>7,'amount'=>'4.25','currency'=>'USD','status'=>'paid','payout_id'=>3);$referrals[15]=(object)array('referral_id'=>15,'affiliate_id'=>7,'amount'=>'5.75','currency'=>'USD','status'=>'paid','payout_id'=>3);$payouts[3]=(object)array('payout_id'=>3,'affiliate_id'=>7,'referrals'=>array(14,15),'amount'=>'10.00','payout_method'=>'manual','status'=>'paid','date'=>'2030-03-01 20:00:00');$referrals[15]->payout_id=0;$referrals[15]->status='unpaid';$before_repair_creates=$creates;$repair=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9014,'referral_ids'=>array(14,15))),'repair'));m7_assert(200===m7_status($repair)&&$before_repair_creates===$creates&&3===(int)$referrals[15]->payout_id&&'paid'===$referrals[15]->status,'partial repair uses provider row update and status API');
$referrals[16]=(object)array('referral_id'=>16,'affiliate_id'=>7,'amount'=>'4.25','currency'=>'USD','status'=>'paid','payout_id'=>4);$referrals[17]=(object)array('referral_id'=>17,'affiliate_id'=>7,'amount'=>'5.75','currency'=>'USD','status'=>'paid','payout_id'=>5);$payouts[4]=(object)array('payout_id'=>4,'affiliate_id'=>7,'referrals'=>array(16,17),'amount'=>'10.00','payout_method'=>'manual','status'=>'paid','date'=>'2030-03-01 20:00:00');$payouts[5]=(object)array('payout_id'=>5,'affiliate_id'=>7,'referrals'=>array(16,17),'amount'=>'10.00','payout_method'=>'manual','status'=>'paid','date'=>'2030-03-01 20:00:00');$before_ambiguous_creates=$creates;$ambiguous=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9015,'referral_ids'=>array(16,17))),'ambiguous'));m7_assert(503===m7_status($ambiguous)&&$before_ambiguous_creates===$creates,'ambiguous recovery fails closed without creating a payout');
 $referrals[18]=(object)array('referral_id'=>18,'affiliate_id'=>7,'amount'=>'4.25','currency'=>'USD','status'=>'unpaid','payout_id'=>0);$referrals[19]=(object)array('referral_id'=>19,'affiliate_id'=>7,'amount'=>'5.75','currency'=>'USD','status'=>'unpaid','payout_id'=>0);$payouts[6]=(object)array('payout_id'=>6,'affiliate_id'=>7,'referrals'=>array(18,19),'amount'=>'10.00','payout_method'=>'manual','status'=>'paid','date'=>'2030-03-02 20:00:00');$payouts[7]=(object)array('payout_id'=>7,'affiliate_id'=>7,'referrals'=>array(99),'amount'=>'99.00','payout_method'=>'manual','status'=>'paid','date'=>'2030-03-02 20:00:00');$before_zero_write_creates=$creates;$zero_write=YBY_Connector::dispatch_payout_complete(m7_req(m7_body(array('erp_payout_request_id'=>9016,'referral_ids'=>array(18,19),'paid_at'=>'2030-03-02')),'zero-write'));m7_assert(200===m7_status($zero_write)&&6===(int)m7_data($zero_write)['data']['payout_id']&&$before_zero_write_creates===$creates&&6===(int)$referrals[18]->payout_id&&6===(int)$referrals[19]->payout_id&&'paid'===$referrals[18]->status&&'paid'===$referrals[19]->status,'zero-write recovery ignores unrelated same-affiliate/date payout and adopts exact payout');
$serialized=serialize($wpdb).serialize($options).serialize($payouts);m7_assert(false===strpos($serialized,'txn-secret-never-stored'),'transaction ID never persisted');YBY_Connector::register_routes();m7_assert(14===count($routes)&&isset($routes['andy-core/v1/erp/affiliates/check'])&&isset($routes['andy-core/v1/erp/payouts/complete'])&&isset($routes['andy-core/v1/erp/wordpress/users/(?P<user_id>\\d+)/password']),'KOL create contract routes');echo "Connector M7 payout harness passed.\n";
