<?php
$root = dirname( __DIR__ );
$assert = function ( $ok, $message ) { if ( ! $ok ) { fwrite( STDERR, "FAIL {$message}\n" ); exit( 1 ); } };
$contains = function ( $source, $contract ) {
	$tokens  = preg_split( '/\s+/', trim( $contract ) );
	$pattern = implode( '\\s+', array_map( function ( $token ) { return preg_quote( $token, '/' ); }, $tokens ) );
	return 1 === preg_match( '/' . $pattern . '/s', $source );
};
$popup = file_get_contents( $root . '/inc/class-yby-global-popup.php' );
$js = file_get_contents( $root . '/public/js/yby-global-popup.js' );
$admin = file_get_contents( $root . '/admin/class-yby-popup-admin.php' );
$css = file_get_contents( $root . '/public/css/yby-global-popup.css' );
$core = file_get_contents( $root . '/inc/class-yby-core.php' );
$inquiry = file_get_contents( $root . '/inc/class-yby-inquiry-shortcodes.php' );
$subscribe = file_get_contents( $root . '/inc/class-yby-subscribe-shortcode.php' );
$renderer = file_get_contents( $root . '/inc/class-yby-inquiry-renderer.php' );
$admin_view = file_get_contents( $root . '/admin/views/popup-settings.php' );
$public = file_get_contents( $root . '/public/class-yby-public.php' );
$assert( $contains( $core, "class-yby-global-popup.php" ) && $contains( $core, '$global_popup = new YBY_Global_Popup( $inquiry_manager, $inquiry_renderer );' ), 'Core must instantiate one global popup with the canonical inquiry manager and renderer.' );
$assert( $contains( $core, 'new YBY_Inquiry_Shortcodes( $inquiry_manager, $inquiry_renderer )' ) && $contains( $core, "wp_footer', " . '$global_popup' ), 'Core must share the same renderer with legacy shortcodes and Global Popup.' );
$assert( $contains( $core, '$subscribe_shortcode = new YBY_Subscribe_Shortcode()' ) && $contains( $core, "'init', " . '$subscribe_shortcode, ' . "'register'" ), 'Core must register the subscribe shortcode through its own class.' );
$assert( $contains( $subscribe, "public function register()" ) && $contains( $subscribe, "add_shortcode( 'yby_subscribe'" ), 'Subscribe shortcode ownership must remain in its own class.' );
$assert( false === strpos( $inquiry, "'yby_subscribe'" ), 'Inquiry shortcodes must not register the subscribe shortcode.' );
$assert( $contains( $core, "class-yby-inquiry-renderer.php" ) && $contains( $popup, '$this->renderer->render_modal(' ), 'Inquiry must reuse the canonical renderer.' );
$assert( $contains( $popup, '$this->renderer->render_modal(' ) && false === strpos( $popup, 'new YBY_Inquiry_Renderer' ), 'Global Popup must render through its injected renderer.' );
$assert( false !== strpos( $popup, "apply_filters( 'yby_inquiry_default_preset'" ) && false === strpos( $popup, "get_preset( 'irrigation_quick_inquiry' )" ), 'Global Popup must resolve its preset through the shared default-preset filter instead of hard-coding irrigation.' );
$assert( $contains( $popup, "const OPTION = 'yby_core_popup_settings'" ) && $contains( $admin, 'update_option( YBY_Global_Popup::OPTION' ), 'Popup settings must use a WordPress option.' );
$assert( false !== strpos( $popup, 'data-yby-subscribe-contract' ) && false !== strpos( $popup, 'not configured' ), 'Subscribe must expose missing authority clearly.' );
$assert( false !== strpos( $js, 'data-yby-popup-open' ) && false !== strpos( $js, 'page_profile' ) && false !== strpos( $js, 'trigger_source' ), 'Trigger context contract missing.' );
$assert( false !== strpos( $js, 'Escape' ) && false !== strpos( $js, 'focusable' ) && false !== strpos( $js, 'data-yby-popup-close' ), 'Accessible close and focus behavior missing.' );
$assert( false !== strpos( $css, '--yby-theme-primary' ) && false !== strpos( $css, '@media' ), 'Responsive Brand Theme popup styling missing.' );
$assert( false !== strpos( $renderer, "yby-inquiry-modal__subtitle" ) && false !== strpos( $popup, "'subtitle' => " . '$settings[\'inquiry_subtitle\']' ), 'Global inquiry subtitle must use the canonical renderer and remain optional.' );
$assert( false !== strpos( $admin_view, 'yby-media-button' ) && false !== strpos( $admin_view, '图片 URL' ) && 2 <= substr_count( $admin_view, 'Preview/Test' ), 'Popup admin must retain image/media controls and separate renderer previews.' );
$assert( false !== strpos( $css, '.yby-global-popup--inquiry' ) && false !== strpos( $css, '--yby-theme-surface' ), 'Global inquiry shell must inherit Brand Theme tokens in a scoped override.' );
$assert( false !== strpos( $css, '--yby-theme-border' ) && false !== strpos( $css, '--yby-theme-overlay' ), 'Global inquiry controls and overlay must inherit scoped Brand Theme tokens.' );
$assert( false === strpos( $popup, 'CREATE TABLE' ) && false === strpos( $popup, 'dbDelta' ), 'Popup must not change database schema.' );
$assert( false !== strpos( $admin, "'Email', 'Email'" ) && false !== strpos( $admin_view, 'nav-tab-wrapper' ), 'Email hub must retain the legacy slug and use WordPress nav tabs.' );
$assert( false !== strpos( $admin_view, "'floating_inquiry' => '悬浮询盘'" ) && strpos( $admin_view, "'floating_inquiry' => '悬浮询盘'" ) < strpos( $admin_view, "'popup_inquiry' => '弹窗询盘'" ) && false !== strpos( $admin_view, "'shortcode_inquiry' => '短代码询盘', 'shortcode_subscribe' => '短代码订阅', 'bulk_marketing' => '营销群发'" ), 'Email hub must expose seven Chinese tabs with 悬浮询盘 first.' );
$assert( false !== strpos( $admin, 'popup_lottery' ) && false !== strpos( $admin, 'bulk_marketing' ) && false !== strpos( $admin, "'inquiry' => 'popup_inquiry'" ), 'Email hub modes and legacy aliases missing.' );
$assert( false !== strpos( $popup, 'inquiry_shortcode_custom_css' ) && false !== strpos( $popup, 'subscribe_shortcode_custom_css' ), 'Inquiry and Subscribe shortcode CSS keys must be independent.' );
$assert( false !== strpos( $admin, 'array_merge( $existing' ), 'Partial tab saves must merge with existing settings.' );
$assert( false !== strpos( $admin_view, "\$popup_css_key = \$popup_prefix . '_custom_css'" ) && false !== strpos( $admin_view, "\$shortcode_key = \$shortcode_prefix . '_shortcode_custom_css'" ), 'Popup and shortcode CSS fields must be mapped independently.' );
$assert( false !== strpos( $admin_view, '.yby-global-popup--inquiry' ) && false !== strpos( $admin_view, '.yby-global-popup--subscribe' ) && false !== strpos( $admin_view, '.yby-shortcode-inquiry' ) && false !== strpos( $admin_view, '.yby-shortcode-subscribe' ), 'All four CSS scopes must be explicit.' );
$assert( false !== strpos( $admin_view, '后续设计' ) && false !== strpos( $admin_view, '后续接入群发系统' ), 'Lottery and bulk marketing placeholders missing.' );
$assert( false !== strpos( $public, "\$popup_settings['inquiry_custom_css']" ) && false !== strpos( $public, "\$popup_settings['subscribe_custom_css']" ) && false !== strpos( $public, "\$popup_settings['inquiry_shortcode_custom_css']" ) && false !== strpos( $public, "\$popup_settings['subscribe_shortcode_custom_css']" ), 'Four independent frontend CSS injections missing.' );
$assert( false !== strpos( $admin_view, '[yby_inquiry]' ) && false !== strpos( $admin_view, '[yby_subscribe]' ) && false !== strpos( $admin_view, '当前嵌入效果' ) && false !== strpos( $admin_view, 'inert' ), 'Shortcode usage, heading, and inert preview contract missing.' );
$forbidden_combined_css = "inquiry_shortcode_custom_css'] . " . '$settings[\'subscribe_shortcode_custom_css';
$assert( false !== strpos( $admin_view, '$settings[ $shortcode_key ]' ) && false === strpos( $admin, $forbidden_combined_css ), 'Shortcode preview must apply only the current saved tab CSS.' );
$assert( false !== strpos( $admin_view, 'render_inline_shortcode()' ) && false !== strpos( $admin_view, '->render();' ), 'Shortcode preview must use canonical renderer implementations.' );
$assert( false !== strpos( $popup, "subscribe_shortcode_show_title' => 0" ) && false !== strpos( $popup, "subscribe_shortcode_show_subtitle' => 0" ) && false !== strpos( $popup, "subscribe_shortcode_show_image' => 0" ), 'Subscribe shortcode display defaults must be off.' );
$assert( false !== strpos( $admin_view, 'type="hidden"' ) && false !== strpos( $admin_view, '显示 Title' ) && false !== strpos( $admin_view, '显示 Subtitle' ) && false !== strpos( $admin_view, '显示 Image' ), 'Subscribe shortcode must expose independent checkbox controls with hidden off values.' );
$assert( false !== strpos( $subscribe, 'placeholder="EMAIL ADDRESS"' ) && false !== strpos( $subscribe, 'aria-label="EMAIL ADDRESS"' ) && false !== strpos( $subscribe, 'data-yby-subscribe-status aria-live="polite"></p>' ), 'Subscribe shortcode must render compact accessible markup with an empty status.' );
$assert( false !== strpos( $subscribe, "'image' => \$settings['subscribe_image']" ), 'Subscribe image toggle must use the existing subscribe_image setting.' );
$assert( false === strpos( $subscribe, 'Subscribe submission is not configured yet.' ) && false === strpos( $subscribe, '<label>Email' ), 'Compact subscribe defaults must omit provider text and email label.' );
$shortcode_css = file_get_contents( $root . '/public/css/yby-email-shortcodes.css' );
$assert( false !== strpos( $shortcode_css, 'display:flex' ) && false !== strpos( $shortcode_css, 'flex-direction:column' ) && false !== strpos( $shortcode_css, '[data-yby-subscribe-status]:empty' ), 'Subscribe shortcode CSS must provide horizontal and mobile layouts.' );
$assert( false !== strpos( $shortcode_css, 'background:var(--yby-theme-surface,#fff)' ) && false !== strpos( $shortcode_css, 'border-radius:var(--yby-theme-border-radius,12px)' ), 'Inquiry shortcode surface and radius contract must remain.' );
$assert( false !== strpos( $admin_view, '统一管理网站 Email 弹窗、短代码和后续营销能力' ) && false !== strpos( $admin_view, '不会影响弹窗或其他组件' ) && false !== strpos( $admin_view, '不会改变短代码样式' ), 'Email usage and CSS-scope explanations must remain visible.' );
echo "PASS global-popup-contract-harness\n";
