<?php
$root = dirname( __DIR__ );
$database = file_get_contents( $root . '/inc/class-yby-database.php' );
$management = file_get_contents( $root . '/inc/class-yby-lead-management.php' );
$security = file_get_contents( $root . '/inc/class-yby-security.php' );
$admin = file_get_contents( $root . '/admin/class-yby-inquiry-admin.php' );
$settings = file_get_contents( $root . '/admin/class-yby-admin.php' );
$view = file_get_contents( $root . '/admin/views/settings-page.php' );
$list_view = file_get_contents( $root . '/admin/views/inquiry-list.php' );
$architecture = file_get_contents( $root . '/docs/v1.5.1/ANDY_CORE_V1_5_1_ADMIN_ARCHITECTURE_AUDIT.md' );
$assert = static function ( $condition, $message ) {
	if ( ! $condition ) { throw new RuntimeException( $message ); }
};
$assert( strpos( $database, "const MANAGEMENT_TABLE = 'yby_lead_management'" ) !== false, 'Management table contract missing.' );
$assert( strpos( $database, "const ACTIVITIES_TABLE = 'yby_lead_activities'" ) !== false, 'Activities table contract missing.' );
$assert( substr_count( $database, 'dbDelta(' ) >= 3, 'Migration must use idempotent dbDelta.' );
$assert( strpos( $database, 'create_management_tables' ) !== false, 'Management migration is not wired.' );
$assert( strpos( $database, 'SHOW INDEX FROM' ) !== false, 'Migration must verify required indexes.' );
$assert( strpos( $management, 'UNIQUE' ) === false, 'Management service must not recreate schema.' );
$assert( strpos( $management, 'LIMIT 50' ) !== false, 'Activities must be bounded.' );
$assert( strpos( $management, 'project_details' ) === false, 'Inbox list must not load full project details.' );
$assert( strpos( $admin, "return 'andy-core-leads'" ) !== false, 'Inquiry slug missing.' );
$studio = file_get_contents( $root . '/admin/class-yby-project-studio.php' );
$assert( strpos( $studio, "return 'yby-project-studio'" ) !== false, 'Dedicated Project Studio submenu slug missing.' );
$assert( strpos( $studio, '$this->studio_page_hook = add_submenu_page' ) !== false, 'Project Studio must retain the real admin page hook.' );
$assert( strpos( $studio, "'page' => self::studio_page_slug()" ) !== false, 'Project Studio URLs must use the dedicated submenu slug.' );
$assert( strpos( $admin, '$this->page_hook = add_submenu_page' ) !== false, 'Inquiry must retain the real admin page hook.' );
$assert( strpos( $admin, 'self::$registered_page_hook = $this->page_hook' ) !== false, 'Inquiry must retain the registered admin page hook.' );
$assert( strpos( $admin, 'filemtime( $file )' ) !== false, 'Inquiry assets must use file modification time for cache busting.' );
$assert( strpos( $admin, "'assets/css/yby-inquiry-admin.css' )" ) !== false && strpos( $admin, "'assets/js/yby-inquiry-admin.js' )" ) !== false, 'Inquiry CSS and JS must use file-based asset versions.' );
$assert( strpos( $admin, 'array(), $this->version )' ) === false, 'Inquiry assets must not use the fixed plugin version.' );
$assert( strpos( $admin, '$is_inquiry_request' ) !== false, 'Inquiry asset fallback missing.' );
$detail_view = file_get_contents( $root . '/admin/views/inquiry-detail.php' );
$settings_view = file_get_contents( $root . '/admin/views/inquiry-settings.php' );
$css = file_get_contents( $root . '/assets/css/yby-inquiry-admin.css' );
$assert( strpos( $detail_view, 'yby-inquiry-detail-form' ) !== false && strpos( $detail_view, '<select name="owner_user_id"' ) !== false, 'Follow-up layout or Owner selector missing.' );
$assert( strpos( $detail_view, 'owner_dropdown_options' ) !== false && strpos( $detail_view, 'owner_display_name' ) !== false, 'Owner dropdown display contract missing.' );
$assert( strpos( $settings_view, 'Active Inquiry Owners' ) !== false && strpos( $settings_view, "'role' => 'salesperson'" ) !== false && strpos( $settings_view, 'Disabling an owner does not remove access' ) !== false && strpos( $settings_view, 'Unassigned' ) !== false, 'Active Inquiry Owners settings missing.' );
$assert( strpos( $css, 'grid-template-columns:160px' ) !== false && strpos( $css, 'yby-inquiry-actions' ) !== false, 'Follow-up layout CSS missing.' );
$assert( strpos( $settings, 'system-status' ) !== false, 'Settings tab allowlist missing.' );
$assert( substr_count( $view, 'nav-tab') >= 3, 'General Settings tabs missing.' );
$assert( strpos( $admin, "'owner_user_id'" ) !== false, 'Owner filtering contract missing.' );
$assert( strpos( $admin, "'page_profile'" ) !== false, 'Page profile filtering contract missing.' );
$assert( strpos( $admin, "'archived'" ) !== false, 'Archive filtering contract missing.' );
$assert( strpos( $management, 'archived_at IS NULL' ) !== false, 'Archive filtering SQL missing.' );
$assert( strpos( $management, 'follow_up_scheduled' ) !== false, 'Follow-up activity contract missing.' );
$assert( strpos( $list_view, 'paginate_links' ) !== false, 'Inquiry list pagination UI missing.' );
$assert( strpos( $architecture, 'Project Studio' ) !== false && strpos( $architecture, 'Social Login' ) !== false, 'Admin architecture audit incomplete.' );
$assert( strpos( $architecture, 'andy_core_leads_view' ) !== false, 'Inquiry capability audit missing.' );
$assert( strpos( $management, 'normalize_datetime' ) !== false && strpos( $management, 'format_datetime_local' ) !== false, 'Datetime conversion contract missing.' );
$assert( strpos( $management, "'owner_changed'" ) !== false, 'Owner activity contract missing.' );
$assert( strpos( $management, "'success' => false" ) !== false, 'Management failure result contract missing.' );
$assert( strpos( $management, 'is_existing_owner_valid_for_record' ) !== false && strpos( $management, 'can_manage_leads' ) !== false && strpos( $management, 'can_assign_leads' ) !== false, 'Owner assignment validation split missing.' );
$assert( strpos( $security, "'salesperson'" ) !== false && strpos( $security, 'active_owner_ids' ) !== false && strpos( $security, 'is_active_owner' ) !== false && strpos( $security, 'is_assignable_owner' ) !== false && strpos( $security, 'is_existing_owner_valid_for_record' ) !== false && strpos( $security, 'is_restricted_salesperson' ) !== false, 'Salesperson role identity and active owner split missing.' );
$assert( strpos( $database, "update_option( self::VERSION_OPTION" ) !== false && strpos( $database, 'management_tables_exist' ) !== false, 'Migration verification contract missing.' );
echo "PASS inquiry-inbox-contract-harness\n";
