<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<div class="wrap"><h1>Andy Core</h1><h2 class="nav-tab-wrapper"><?php foreach ( array( 'general' => 'General', 'inquiry' => 'Inquiry', 'system-status' => 'System Status' ) as $key => $label ) : ?><a class="nav-tab <?php echo 'inquiry' === $key ? 'nav-tab-active' : ''; ?>" href="<?php echo esc_url( add_query_arg( array( 'page' => YBY_Helpers::admin_page_slug(), 'tab' => $key ), admin_url( 'admin.php' ) ) ); ?>"><?php echo esc_html( $label ); ?></a><?php endforeach; ?></h2>
	<?php if ( $notice ) : ?><div class="notice notice-success"><p><?php echo esc_html( $notice ); ?></p></div><?php endif; ?><form method="post"><?php wp_nonce_field( 'yby_inquiry_settings_save', 'yby_inquiry_settings_nonce' ); ?><input type="hidden" name="yby_inquiry_settings_submit" value="1"><table class="form-table">
	<tr><th>Default status</th><td><select name="yby_inquiry_settings[default_status]"><?php foreach ( YBY_Lead_Management::STATUSES as $value ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $options['default_status'], $value ); ?>><?php echo esc_html( $value ); ?></option><?php endforeach; ?></select></td></tr>
	<tr><th>Default priority</th><td><select name="yby_inquiry_settings[default_priority]"><?php foreach ( YBY_Lead_Management::PRIORITIES as $value ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $options['default_priority'], $value ); ?>><?php echo esc_html( $value ); ?></option><?php endforeach; ?></select></td></tr>
	<tr><th>Active Inquiry Owners</th><td><p class="description">Only users with the Salesperson role are listed. Active owners may receive new Inquiry assignments. Disabling an owner does not remove access to their existing assigned inquiries.</p><?php foreach ( get_users( array( 'role' => 'salesperson', 'fields' => array( 'ID', 'display_name' ) ) ) as $user ) : ?><label><input type="checkbox" name="yby_inquiry_settings[salespeople][]" value="<?php echo esc_attr( $user->ID ); ?>" <?php checked( in_array( (int) $user->ID, (array) $options['salespeople'], true ) ); ?>> <?php echo esc_html( $user->display_name ); ?></label><br><?php endforeach; ?></td></tr>
	<tr><th>Default Owner</th><td><select name="yby_inquiry_settings[default_owner_user_id]"><option value="0" <?php selected( $options['default_owner_user_id'], 0 ); ?>>Unassigned</option><?php foreach ( $options['salespeople'] as $user_id ) : $user = get_user_by( 'id', $user_id ); ?><option value="<?php echo esc_attr( $user_id ); ?>" <?php selected( $options['default_owner_user_id'], $user_id ); ?>><?php echo esc_html( $user->display_name ); ?></option><?php endforeach; ?></select></td></tr>
	<tr><th>Leads per page</th><td><select name="yby_inquiry_settings[leads_per_page]"><?php foreach ( array( 30, 50, 100 ) as $value ) : ?><option value="<?php echo esc_attr( $value ); ?>" <?php selected( $options['leads_per_page'], $value ); ?>><?php echo esc_html( $value ); ?></option><?php endforeach; ?></select></td></tr>
	<tr><th>Editors can manage</th><td><label><input type="checkbox" name="yby_inquiry_settings[editors_can_manage]" value="1" <?php checked( $options['editors_can_manage'] ); ?>> Enabled</label></td></tr><tr><th>Assignment enabled</th><td><label><input type="checkbox" name="yby_inquiry_settings[assignment_enabled]" value="1" <?php checked( $options['assignment_enabled'] ); ?>> Enabled</label></td></tr><tr><th>Archive behavior</th><td><select name="yby_inquiry_settings[archive_behavior]"><option value="soft" selected>Soft archive</option></select></td></tr>
	</table><p><button class="button button-primary" type="submit">Save Inquiry Settings</button></p></form>
</div>
